CorlateCode-master/src/Feature/PageContent/code/Corlate.Feature.PageContent/Controllers/BlogsController.cs
namespace Corlate.Feature.PageContent.Controllers
{
    using Foundation.Common.Models;
    using Foundation.Common.Utilities;
    using Models;
    using Sitecore.Data;
    using Sitecore.Data.Items;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    public class BlogsController : Controller
    {
        #region ACTION METHODS

        public ActionResult RenderBlog()
        {
            Blog viewModel = null;

            try
            {
                viewModel = GetBlogByPage("1", "");
            }
            catch (System.Exception ex)
            {
                LogManager.SaveLog(System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.Name + "." + System.Reflection.MethodBase.GetCurrentMethod().Name, ex, LogManager.LogTypes.Error, string.Empty);
            }

            return View(GlobalConstants.SUBLAYOUTS_PATH + "PageContent/Blog.cshtml", viewModel);
        }

        public ActionResult GetBlog(string pageNumber, string currentBlogItemID)
        {
            Blog viewModel = null;

            if (!string.IsNullOrEmpty(pageNumber) && !string.IsNullOrEmpty(currentBlogItemID))
            {
                try
                {
                    viewModel = GetBlogByPage(pageNumber, currentBlogItemID);
                }
                catch (System.Exception ex)
                {
                    LogManager.SaveLog(System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.Name + "." + System.Reflection.MethodBase.GetCurrentMethod().Name, ex, LogManager.LogTypes.Error, string.Empty);
                }
            }

            return PartialView(GlobalConstants.SUBLAYOUTS_PATH + "PageContent/_BlogDetails.cshtml", viewModel);
        }

        public ActionResult RenderPopularPosts()
        {
            PopularPostsSource viewModel = null;

            try
            {
                //get the datasource item assigned to the rendering
                Item renderingDatasourceItem = SitecoreUtility.GetRenderingDatasourceItem();

                if (renderingDatasourceItem != null && renderingDatasourceItem.TemplateID == References.Templates.PopularPostsSource.ID)
                {
                    viewModel = new PopularPostsSource(renderingDatasourceItem);

                    if (!viewModel.IsActive)
                    {
                        viewModel = null;
                    }
                    else
                    {
                        viewModel.FeaturedBlogs = GetRelatedPosts(renderingDatasourceItem, References.Templates.PopularPostsSource.Fields.FeaturedBlogs);
                    }
                }
            }
            catch (System.Exception ex)
            {
                LogManager.SaveLog(System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.Name + "." + System.Reflection.MethodBase.GetCurrentMethod().Name, ex, LogManager.LogTypes.Error, string.Empty);
            }

            return View(GlobalConstants.SUBLAYOUTS_PATH + "PageContent/PopularPosts.cshtml", viewModel);
        }

        public ActionResult RenderTagsOrCategoriesSidebarFilter()
        {
            TagsOrCategoriesSidebarFilter viewModel = null;

            try
            {
                string blogArchivePageItemID = SitecoreUtility.GetRenderingParameters(References.Templates.TagsOrCategoriesSidebarFilter.ID, References.Templates.TagsOrCategoriesSidebarFilter.Fields.BlogArchivePage);

                if (!string.IsNullOrEmpty(blogArchivePageItemID))
                {
                    Item blogArchivePageItem = SitecoreUtility.GetItem(new ID(blogArchivePageItemID));

                    if (blogArchivePageItem != null)
                    {
                        viewModel = new TagsOrCategoriesSidebarFilter();
                        viewModel.SectionTitle = SitecoreUtility.GetRenderingParameters(References.Templates.TagsOrCategoriesSidebarFilter.ID, References.Templates.TagsOrCategoriesSidebarFilter.Fields.SectionTitle);
                        viewModel.DisplayItemsAsTags = SitecoreUtility.GetRenderingParameters(References.Templates.TagsOrCategoriesSidebarFilter.ID, References.Templates.TagsOrCategoriesSidebarFilter.Fields.DisplayItemsAsTags) == "1";
                        viewModel.BlogArchivePageURL = SitecoreUtility.GetItemURL(blogArchivePageItem);

                        if (!viewModel.DisplayItemsAsTags)
                        {
                            List<BlogCategory> categoriesUsedByBlogs = new List<BlogCategory>();
                            Item blogCategoriesFolderItem = SitecoreUtility.GetItem(References.Content.BlogCategoriesFolder);

                            if (blogCategoriesFolderItem != null && blogCategoriesFolderItem.HasChildren)
                            {
                                List<Item> activeCategories = SitecoreUtility.GetItemsByTemplate(blogCategoriesFolderItem, References.Templates.BlogCategory.ID)
                                    .Where(x => x.Fields[References.Templates.BlogCategory.Fields.IsActive].Value == "1").ToList();

                                if (activeCategories != null && activeCategories.Count > 0)
                                {
                                    foreach (Item category in activeCategories)
                                    {
                                        if (SitecoreUtility.HasReferrers(category, References.Templates.BlogPage.ID, References.Templates.Blog.Fields.IsActive))
                                        {
                                            BlogCategory blogCategory = new BlogCategory(category);
                                            categoriesUsedByBlogs.Add(blogCategory);
                                        }
                                    }

                                    viewModel.BlogCategories = categoriesUsedByBlogs;
                                }
                            }
                        }
                        else
                        {
                            List<BlogTag> tagsUsedByBlogs = new List<BlogTag>();
                            Item blogTagsFolderItem = SitecoreUtility.GetItem(References.Content.BlogTagsFolder);

                            if (blogTagsFolderItem != null && blogTagsFolderItem.HasChildren)
                            {
                                List<Item> activeTags = SitecoreUtility.GetItemsByTemplate(blogTagsFolderItem, References.Templates.BlogTag.ID)
                                    .Where(x => x.Fields[References.Templates.BlogTag.Fields.IsActive].Value == "1").ToList();

                                if (activeTags != null && activeTags.Count > 0)
                                {
                                    foreach (Item tag in activeTags)
                                    {
                                        if (SitecoreUtility.HasReferrers(tag, References.Templates.BlogPage.ID, References.Templates.Blog.Fields.IsActive))
                                        {
                                            BlogTag blogTag = new BlogTag(tag);
                                            tagsUsedByBlogs.Add(blogTag);
                                        }
                                    }

                                    viewModel.BlogTags = tagsUsedByBlogs;
                                }
                            }
                        }
                    }
                }
            }
            catch (System.Exception ex)
            {
                LogManager.SaveLog(System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.Name + "." + System.Reflection.MethodBase.GetCurrentMethod().Name, ex, LogManager.LogTypes.Error, string.Empty);
            }

            return View(GlobalConstants.SUBLAYOUTS_PATH + "PageContent/TagsOrCategoriesSidebarFilter.cshtml", viewModel);
        }

        public ActionResult RenderBlogArchive(string page, string cat, string tag)
        {
            BlogArchive viewModel = new BlogArchive();

            try
            {
                int totalPages;
                int selectedPage = Sitecore.MainUtil.GetInt(page, 1);
                viewModel.SelectedCategoryID = cat;
                viewModel.SelectedTagID = tag;
                viewModel.BlogArchivePageItemID = System.Convert.ToString(Sitecore.Context.Item.ID);
                viewModel.BlogTeasers = GetBlogTeasersByFilters(selectedPage, cat, tag, viewModel.BlogArchivePageItemID, out totalPages);
                viewModel.Pagination = GetPagination(selectedPage, totalPages);
            }
            catch (System.Exception ex)
            {
                LogManager.SaveLog(System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.Name + "." + System.Reflection.MethodBase.GetCurrentMethod().Name, ex, LogManager.LogTypes.Error, string.Empty);
            }

            return View(GlobalConstants.SUBLAYOUTS_PATH + "PageContent/BlogArchive.cshtml", viewModel);
        }

        public ActionResult GetBlogTeasers(string pageNumber, string categoryID, string tagID, string blogArchivePageItemID)
        {
            BlogArchive viewModel = new BlogArchive();

            try
            {
                int totalPages;
                int selectedPage = Sitecore.MainUtil.GetInt(pageNumber, 1);
                viewModel.SelectedCategoryID = categoryID;
                viewModel.SelectedTagID = tagID;
                viewModel.BlogArchivePageItemID = blogArchivePageItemID;
                viewModel.BlogTeasers = GetBlogTeasersByFilters(selectedPage, categoryID, tagID, blogArchivePageItemID, out totalPages);
                viewModel.Pagination = GetPagination(selectedPage, totalPages);
            }
            catch (System.Exception ex)
            {

CorlateCode-master/src/Feature/PageContent/code/Corlate.Feature.PageContent/Controllers/ContactUsController.cs
namespace Corlate.Feature.PageContent.Controllers
{
    using Corlate.Feature.PageContent.Models;
    using Corlate.Foundation.Common.Models;
    using Corlate.Foundation.Common.Utilities;
    using Sitecore.Data;
    using Sitecore.Data.Items;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public class ContactUsController : Controller
    {
        public ActionResult RenderContactUsForm()
        {
            ContactUsFormSource viewModel = null;

            try
            {
                //get the datasource item assigned to the rendering
                Item renderingDatasourceItem = SitecoreUtility.GetRenderingDatasourceItem();

                if (renderingDatasourceItem != null && renderingDatasourceItem.TemplateID == References.Templates.ContactUsFormSource.ID)
                {
                    viewModel = new ContactUsFormSource(renderingDatasourceItem);

                    if (!viewModel.IsActive)
                    {
                        viewModel = null;
                    }
                    else
                    {
                        //get the list of items selected in the multilist field
                        IList<Item> featuredItems = SitecoreUtility.GetSelectedItemsInMultilistField(viewModel.InnerItem, References.Templates.ContactUsFormSource.Fields.SocialNetworkLinks);

                        //check for each item if it is of valid template and active.If yes, then add it to the list
                        if (featuredItems != null && featuredItems.Count > 0)
                        {
                            viewModel.SocialNetworkLinks = new List<FooterSocialLink>();

                            foreach (Item featuredItem in featuredItems)
                            {
                                if (featuredItem.TemplateID == References.Templates.FooterSocialLink.ID)
                                {
                                    FooterSocialLink oblFeaturedItem = new FooterSocialLink(featuredItem);

                                    if (oblFeaturedItem != null && oblFeaturedItem.IsActive)
                                    {
                                        viewModel.SocialNetworkLinks.Add(oblFeaturedItem);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            catch (System.Exception ex)
            {
                LogManager.SaveLog(System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.Name + "." + System.Reflection.MethodBase.GetCurrentMethod().Name, ex, LogManager.LogTypes.Error, string.Empty);
            }

            return View(GlobalConstants.SUBLAYOUTS_PATH + "PageContent/ContactUsForm.cshtml", viewModel);
        }

        /// <summary>
        /// get the form data and save as an item
        /// </summary>
        /// <param name="contactUsFormDataModel"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SaveContactUsFormData(ContactUsFormData contactUsFormDataModel)
        {
            string statusCode = "0";
            string statusMessage = string.Empty;

            try
            {
                List<KeyValuePair<ID, string>> fieldValueCollection = new List<KeyValuePair<ID, string>>();                
                fieldValueCollection.Add(new KeyValuePair<ID, string>(References.Templates.ContactUsFormData.Fields.FullName, contactUsFormDataModel.Fullname));
                fieldValueCollection.Add(new KeyValuePair<ID, string>(References.Templates.ContactUsFormData.Fields.Email, contactUsFormDataModel.Email));
                fieldValueCollection.Add(new KeyValuePair<ID, string>(References.Templates.ContactUsFormData.Fields.Subject, contactUsFormDataModel.Subject));
                fieldValueCollection.Add(new KeyValuePair<ID, string>(References.Templates.ContactUsFormData.Fields.Comments, contactUsFormDataModel.Comments));
                string itemName = contactUsFormDataModel.Email.Replace("@", "").Replace(".","") + SitecoreUtility.GenerateRandomNumber(5);
                
                Item newItem = SitecoreUtility.CreateItem(itemName, References.Content.ContactUsFormDataFolder, References.Templates.ContactUsFormData.ID.ToString(), fieldValueCollection);

                if (newItem != null)
                {
                    statusCode = "1";
                    statusMessage = "We've received your message and will get back to you shortly.";
                }
                else
                {
                    statusCode = "0";
                    statusMessage = "A problem occurred while processing your request. Please try again later.";
                }
            }
            catch (System.Exception ex)
            {
                LogManager.SaveLog(System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.Name + "." + System.Reflection.MethodBase.GetCurrentMethod().Name, ex, LogManager.LogTypes.Error, string.Empty);
                statusCode = "0";
                statusMessage = "A problem occurred while processing your request. Please try again later.";
            }

            return Json(new { Status = statusCode, Message = statusMessage }, JsonRequestBehavior.AllowGet);
        }
    }
}

CorlateCode-master/src/Feature/PageContent/code/Corlate.Feature.PageContent/Controllers/FacetsController.cs
namespace Corlate.Feature.PageContent.Controllers
{
    using Corlate.Feature.PageContent.Models;
    using Corlate.Foundation.Common.Models;
    using Corlate.Foundation.Common.Utilities;
    using Sitecore.Data.Items;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    public class FacetsController : Controller
    {
        public ActionResult RenderFacets()
        {
            FacetsSource viewModel = null;

            try
            {
                //get the datasource item assigned to the rendering
                Item renderingDatasourceItem = SitecoreUtility.GetRenderingDatasourceItem();

                if (renderingDatasourceItem != null && renderingDatasourceItem.TemplateID == References.Templates.FacetsSource.ID)
                {
                    viewModel = new FacetsSource(renderingDatasourceItem);

                    if (!viewModel.IsActive)
                    {
                        viewModel = null;
                    }
                    else
                    {
                        List<Item> selectedItems = SitecoreUtility.GetSelectedItemsInMultilistField(renderingDatasourceItem, References.Templates.FacetsSource.Fields.Facets)
                            .Where(x => x.Fields[References.Templates.Facet.Fields.IsActive].Value == "1").ToList();

                        if (selectedItems != null && selectedItems.Count > 0)
                        {
                            viewModel.Facets = new List<Facet>();

                            foreach (Item item in selectedItems)
                            {
                                Facet featuredItem = new Facet(item);
                                viewModel.Facets.Add(featuredItem);
                            }
                        }
                    }
                }
            }
            catch (System.Exception ex)
            {
                LogManager.SaveLog(System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.Name + "." + System.Reflection.MethodBase.GetCurrentMethod().Name, ex, LogManager.LogTypes.Error, string.Empty);
            }

            return View(GlobalConstants.SUBLAYOUTS_PATH + "PageContent/Facets.cshtml", viewModel);
        }
    }
}

CorlateCode-master/src/Feature/PageContent/code/Corlate.Feature.PageContent/Views/Corlate/University/Sublayouts/PageContent/Banner.cshtml
@using Corlate.Feature.PageContent.Models
@using Sitecore.Mvc
@model Banner
@{
    Layout = null;
}

@if (Model != null)
{
    <!--=========== BEGIN COURSE BANNER SECTION ================-->
    <section id="imgBanner" style="background-image:url(@Model.ImageURL)">
        <h2>@Html.Sitecore().Field(Model.TitleID, Model.InnerItem)</h2>
    </section>
    <!--=========== END COURSE BANNER SECTION ================-->
}
else
{
    <span></span>
}

CorlateCode-master/src/Feature/PageContent/code/Corlate.Feature.PageContent/Views/Corlate/University/Sublayouts/PageContent/ContactUsForm.cshtml
@using Corlate.Feature.PageContent.Models
@using Sitecore.Mvc
@model ContactUsFormSource
@{
    Layout = null;
    <style>
        .validation-msg{
            font-size: 12px;
            margin-left: 10px;
            color:red;
        }
        .color-success {
            color: forestgreen;
        }

        .color-error {
            color: red;
        }

        #spSubmitStatus {
            margin-left: 10px;
            font-weight: bold;            
        }
    </style>
}

@if (Model != null)
{
    <!--=========== BEGIN CONTACT SECTION ================-->
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="title_area">
                        <h2 class="title_two">@Html.Sitecore().Field(Model.TitleID, Model.InnerItem)</h2>
                        <span></span>
                        @Html.Sitecore().Field(Model.DescriptionID, Model.InnerItem)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8">
                    <div class="contact_form wow fadeInLeft">
                        <form class="submitphoto_form">
                            <div>
                                <span class="validation-msg" id="spFullname"></span>
                                <input type="text" id="txtFullname" class="wp-form-control wpcf7-text" placeholder="Your name">                                
                            </div>
                            <div>
                                <span class="validation-msg" id="spEmail"></span>
                                <input type="text" id="txtEmail" class="wp-form-control wpcf7-email" placeholder="Email address">                                
                            </div>
                            <div>
                                <span class="validation-msg" id="spSubject"></span>
                                <input type="text" id="txtSubject" class="wp-form-control wpcf7-text" placeholder="Subject">                                
                            </div>
                            <div>
                                <span class="validation-msg" id="spComments"></span>
                                <textarea id="txtComments" class="wp-form-control wpcf7-textarea" cols="30" rows="10" placeholder="What would you like to tell us"></textarea>                                
                            </div>
                            <input type="button" id="btnContactUsFormSubmit" value="Submit" class="wpcf7-submit">
                            <span id="spSubmitStatus"></span>
                        </form>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <div class="contact_address wow fadeInRight">
                        @Html.Sitecore().Field(Model.AddressID, Model.InnerItem)
                        <div class="address_group">
                            <ul class="footer_social">
                                @if (Model.SocialNetworkLinks != null && Model.SocialNetworkLinks.Count > 0)
                                {
                                    foreach (FooterSocialLink link in Model.SocialNetworkLinks)
                                    {
                                        <li>
                                            <a href="@link.TargetURL" class="soc_tooltip" title="" data-placement="top" data-toggle="tooltip" data-original-title="@link.Title"><i class="@link.CSSClass"></i></a>
                                        </li>
                                    }
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--=========== END CONTACT SECTION ================-->

    <script>
        jQuery(function ($) {
            'use strict';

            $(function () {

                $("#btnContactUsFormSubmit").click(function () {
                    if (ValidateForm()) {
                        SaveContactUsFormData();
                    }
                });

                function ValidateForm() {
                    $(".validation-msg").html("");
                    $("#spSubmitStatus").html("");                    

                    var reqdMessage = "This field is required";
                    var isValidData = true;
                   
                    if ($("#txtFullname").val().length <= 0) {                       
                        $("#spFullname").html(reqdMessage);
                        isValidData = false;
                    }

                    if ($("#txtEmail").val().length <= 0) {
                        $("#spEmail").html(reqdMessage);
                        isValidData = false;
                    }

                    if ($("#txtSubject").val().length <= 0) {
                        $("#spSubject").html(reqdMessage);
                        isValidData = false;
                    }

                    if ($("#txtComments").val().length <= 0) {
                        $("#spComments").html(reqdMessage);
                        isValidData = false;
                    }

                    return isValidData;
                }

                function SaveContactUsFormData() {
                    var contactUsFormDataModel = {};
                    contactUsFormDataModel.Fullname = $("#txtFullname").val();
                    contactUsFormDataModel.Email = $("#txtEmail").val();
                    contactUsFormDataModel.Subject = $("#txtSubject").val();
                    contactUsFormDataModel.Comments = $("#txtComments").val();

                    $.ajax({
                        url: '@Url.Action("SaveContactUsFormData", "ContactUs")',
                        type: "POST",
                        data: '{contactUsFormDataModel: ' + JSON.stringify(contactUsFormDataModel) + '}',
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: function (response) {
                            console.log(response.Status + "-" + response.Message);
                            if (response.Status == "1") {
                                $('input[type="text"]').val('');
                                $('textarea').val('');
                                $("#spSubmitStatus").html(response.Message).removeClass("color-error").addClass("color-success").fadeIn;
                            }
                            else if (response.Status == "0") {
                                $("#spSubmitStatus").html(response.Message).removeClass("color-success").addClass("color-error").fadeIn;
                            }

                            //fadeout the message after a few seconds
                            setTimeout(function () { $("#spSubmitStatus").fadeOut() }, 5000);
                        },
                        error: function (data) {
                            console.log("error", data);
                        }
                    });
                }
            });


        });

    </script>
}
else
{
    <span></span>
}

CorlateCode-master/src/Feature/PageContent/code/Corlate.Feature.PageContent/Views/Corlate/University/Sublayouts/PageContent/CourseArchive.cshtml
@using Corlate.Feature.PageContent.Models
@model CourseArchive
@{
    Layout = null;
}

@if (Model != null)
{
    <!--=========== BEGIN COURSE ARCHIVE SECTION ================-->
   <section id="courseArchive">
        <div class="container">
            <div class="row">
                
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div id="divCourseTeasersListing" class="courseArchive_content">
                        @Html.Partial(Corlate.Foundation.Common.Models.GlobalConstants.SUBLAYOUTS_PATH + "/PageContent/_CourseTeasersListing.cshtml", Model)
                    </div>
                </div>
               
            </div>
        </div>
    </section>
    <!--=========== END COURSE ARCHIVE SECTION ================-->    
}
else
{
    <span></span>
}

CorlateCode-master/src/Feature/PageContent/code/Corlate.Feature.PageContent/Views/Corlate/University/Sublayouts/PageContent/_BlogTeasersListing.cshtml
@using Corlate.Feature.PageContent.Models
@using Sitecore.Mvc
@model BlogArchive
@{
    Layout = null;
    <style>
        ul.pagination li a {
            cursor: pointer;
        }
    </style>
}

@if (Model != null)
{
    <!-- start blog teasers listing  -->
    <input type="hidden" id="hdnCategoryID" value="@Model.SelectedCategoryID" />
    <input type="hidden" id="hdnTagID" value="@Model.SelectedTagID" />
    <input type="hidden" id="hdnBlogArchivePageItemID" value="@Model.BlogArchivePageItemID" />

    <div class="row">
        @if (Model.BlogTeasers != null && Model.BlogTeasers.Count > 0)
        {
            foreach (Blog blog in Model.BlogTeasers)
            {
                <div class="col-lg-12 col-12 col-sm-12">
                    <div class="single_blog_archive wow fadeInUp">
                        <div class="blogimg_container">
                            <a href="@blog.PageURL" class="blog_img">
                                @Html.Sitecore().Field(blog.ImageID, blog.InnerItem)
                            </a>
                        </div>
                        <h2 class="blog_title"><a href="@blog.PageURL"> @Html.Sitecore().Field(blog.TitleID, blog.InnerItem)</a></h2>
                        <div class="blog_commentbox">
                            @if (!string.IsNullOrEmpty(blog.Author))
                            {
                            <p><i class="fa fa-user"></i>@Html.Sitecore().Field(blog.AuthorID, blog.InnerItem)</p>
                            }
                            @if (!string.IsNullOrEmpty(blog.PostedDate))
                            {
                            <p><i class="fa fa-calendar"></i>@blog.PostedDate</p>
                            }
                        </div>
                        <p class="blog_summary">@Html.Sitecore().Field(blog.BriefDescriptionID, blog.InnerItem)</p>
                        <a class="blog_readmore" href="@blog.PageURL">@Html.Sitecore().Field(blog.ReadMoreLabelID, blog.InnerItem)</a>
                    </div>
                </div>
            }
        }
    </div>
    <!-- end blog teasers listing  -->

    <!--start pagination-->
    if (Model.Pagination.TotalPages > 1)
    {
        <nav>
            <ul class="pagination wow fadeInLeft">
                <li class="@(Model.Pagination.SelectedPage == 1 ? "disabled" : "")">
                    <a onclick="GetBlogTeasers(1)">First</a>
                </li>
                <li class="@(Model.Pagination.SelectedPage == 1 ? "disabled" : "")">
                    <a onclick="GetBlogTeasers(@Model.Pagination.SelectedPage - 1)"><span aria-hidden="true">«</span><span class="sr-only">Previous</span></a>
                </li>
                @for (int index = Model.Pagination.FirstPageNumberInPagination; index <= Model.Pagination.LastPageNumberInPagination; index++)
                {
                    <li class="@(Model.Pagination.SelectedPage == index ? "active" : "")">
                        <a onclick="GetBlogTeasers(@index)">@index</a>
                    </li>
                }
                <li class="@(Model.Pagination.SelectedPage == Model.Pagination.TotalPages ? "disabled" : "")">
                    <a onclick="GetBlogTeasers(@Model.Pagination.SelectedPage + 1)"><span aria-hidden="true">»</span><span class="sr-only">Next</span></a>
                </li>
                <li class="@(Model.Pagination.SelectedPage == Model.Pagination.TotalPages ? "disabled" : "")">
                    <a onclick="GetBlogTeasers(@Model.Pagination.TotalPages)">Last</a>
                </li>
            </ul>
        </nav>
    }
    <!--end pagination-->

    <script>
        function GetBlogTeasers(pgNumber) {
            $.ajax({
                url: '@Url.Action("GetBlogTeasers", "Blogs")',
                type: "GET",
                data: {
                    pageNumber: pgNumber,
                    categoryID: $("#hdnCategoryID").val(),
                    tagID: $("#hdnTagID").val(),
                    blogArchivePageItemID: $("#hdnBlogArchivePageItemID").val()
                },
                dataType: "html",
                context: this,
                success: function (data) {
                    $("#divBlogTeasersListing").html(data);
                },
                error: function (data) {
                    console.log("error", data);
                }
            });            
        }
    </script>
}
else
{
    <span></span>
}